"use strict";
const tokenKey="bh_staff_token",token=()=>sessionStorage.getItem(tokenKey),headers=()=>({"Content-Type":"application/json",Authorization:`Bearer ${token()}`});
const loginView=document.getElementById("loginView"),dashboard=document.getElementById("dashboard"),identity=document.getElementById("identity"),logout=document.getElementById("logout"),notice=document.getElementById("portalNotice");
let currentUser,appointments=[];
function notify(message){notice.textContent=message;notice.classList.add("show");setTimeout(()=>notice.classList.remove("show"),3500)}
async function api(url,options={}){const response=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});if(response.status===401){sessionStorage.removeItem(tokenKey);showLogin();throw new Error("Please sign in again.")}const data=response.status===204?null:await response.json();if(!response.ok)throw new Error(data.error||"Request failed.");return data}
function showLogin(){loginView.hidden=false;dashboard.hidden=true;logout.hidden=true;identity.textContent=""}
async function boot(){if(!token())return showLogin();try{currentUser=await api("/api/me");loginView.hidden=true;dashboard.hidden=false;logout.hidden=false;identity.textContent=`${currentUser.name} · ${currentUser.role}`;document.getElementById("dashboardTitle").textContent=currentUser.role==="admin"?"Administrator dashboard":"Doctor dashboard";document.getElementById("adminTools").hidden=currentUser.role!=="admin";document.getElementById("scheduleTools").hidden=currentUser.role!=="doctor";if(currentUser.role==="admin")await loadDoctors();else await loadSchedule();await loadAppointments()}catch(error){document.getElementById("loginError").textContent=error.message}}
document.getElementById("loginForm").addEventListener("submit",async event=>{event.preventDefault();const error=document.getElementById("loginError");error.textContent="";try{const result=await fetch("/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.target)))}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d});sessionStorage.setItem(tokenKey,result.token);event.target.reset();await boot()}catch(e){error.textContent=e.message}});
logout.addEventListener("click",async()=>{try{await api("/api/logout",{method:"POST"})}catch{}sessionStorage.removeItem(tokenKey);showLogin()});document.getElementById("refresh").addEventListener("click",boot);
async function loadDoctors(){const doctors=await api("/api/admin/doctors"),list=document.getElementById("doctorList");list.replaceChildren();doctors.forEach(d=>{const row=document.createElement("div");row.className="doctor-row";const label=document.createElement("span");label.textContent=`${d.name} — ${d.specialty} · ${d.active?"Active":"Inactive"}`;const button=document.createElement("button");button.className="button-link";button.style.color="var(--teal-dark)";button.textContent=d.active?"Deactivate":"Activate";button.onclick=async()=>{await api(`/api/admin/doctors/${d.id}`,{method:"PATCH",body:JSON.stringify({active:!d.active})});notify("Doctor updated.");loadDoctors()};row.append(label,button);list.append(row)})}
document.getElementById("doctorForm").addEventListener("submit",async event=>{event.preventDefault();try{await api("/api/admin/doctors",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(event.target)))});event.target.reset();notify("Doctor account created.");loadDoctors()}catch(e){notify(e.message)}});
const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
function buildWeek(schedule=[]){const root=document.getElementById("weekSchedule");root.replaceChildren();days.forEach((name,day)=>{const value=schedule.find(x=>x.day===day);const row=document.createElement("div");row.className="day-row";row.dataset.day=day;row.innerHTML=`<label class="day-toggle"><input class="enabled" type="checkbox" ${value?"checked":""}>${name}</label><label>Starts<input class="start" type="time" value="${value?.start||"09:00"}"></label><label>Ends<input class="end" type="time" value="${value?.end||"17:00"}"></label><label>Slot length<select class="duration"><option>15</option><option selected>30</option><option>45</option><option>60</option></select></label>`;row.querySelector(".duration").value=String(value?.slotMinutes||30);root.append(row)})}
async function loadSchedule(){const d=await api("/api/doctor/schedule");buildWeek(d.availability);document.getElementById("unavailableDates").value=(d.unavailableDates||[]).join(", ")}
document.getElementById("scheduleForm").addEventListener("submit",async event=>{event.preventDefault();const availability=[...document.querySelectorAll(".day-row")].filter(r=>r.querySelector(".enabled").checked).map(r=>({day:Number(r.dataset.day),start:r.querySelector(".start").value,end:r.querySelector(".end").value,slotMinutes:Number(r.querySelector(".duration").value)}));const unavailableDates=document.getElementById("unavailableDates").value.split(",").map(x=>x.trim()).filter(Boolean);try{await api("/api/doctor/schedule",{method:"PUT",body:JSON.stringify({availability,unavailableDates})});notify("Schedule published.")}catch(e){notify(e.message)}});
async function loadAppointments(){appointments=await api("/api/appointments");renderAppointments()}
function renderAppointments(){const filter=document.getElementById("statusFilter").value,root=document.getElementById("appointments"),items=appointments.filter(a=>!filter||a.status===filter);root.replaceChildren();if(!items.length){root.innerHTML='<p class="empty">No appointments found.</p>';return}items.forEach(a=>{const card=document.createElement("article");card.className="appointment-card";const when=document.createElement("div");when.className="appointment-time";when.innerHTML=`<strong>${a.date} · ${a.time}</strong><span class="status-pill">${a.status}</span>`;const detail=document.createElement("div");detail.className="appointment-detail";detail.textContent=`${a.fullName} · ${a.phone} · ${a.email||"No email"} · ${a.service} · Ref ${a.reference}${a.message?` · ${a.message}`:""}`;const actions=document.createElement("div");actions.className="appointment-actions";const select=document.createElement("select");["pending","confirmed","completed","cancelled","declined"].forEach(s=>select.add(new Option(s,s,s===a.status,s===a.status)));select.onchange=async()=>{try{await api(`/api/appointments/${a.id}`,{method:"PATCH",body:JSON.stringify({status:select.value})});notify("Appointment updated.");loadAppointments()}catch(e){notify(e.message)}};actions.append(select);card.append(when,detail,actions);root.append(card)})}
document.getElementById("statusFilter").addEventListener("change",renderAppointments);boot();
