const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const net=require('node:net');const path=require('node:path');let server,base;
before(async()=>{const socket=net.createServer();await new Promise(resolve=>socket.listen(0,'127.0.0.1',resolve));const port=socket.address().port;await new Promise(resolve=>socket.close(resolve));base='http://127.0.0.1:'+port;server=spawn(process.execPath,['tests/fixtures/operational-server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port)},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Fixture startup timed out')),10000);server.stdout.on('data',data=>{if(data.toString().includes('listening')){clearTimeout(timer);resolve()}});server.once('exit',code=>{clearTimeout(timer);reject(Error('Fixture exited '+code))})})});
after(()=>server?.kill());
async function request(route,method='GET',body,cookie='',csrf=''){return fetch(base+route,{method,headers:{Origin:base,...(body?{'Content-Type':'application/json'}:{}),...(cookie?{Cookie:cookie}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(body?{body:JSON.stringify(body)}:{})})}
async function login(email){const response=await request('/api/login','POST',{email,password:'FixturePassword123!'});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0];const me=await request('/api/me','GET',null,cookie);assert.equal(me.status,200);return {cookie,user:await me.json()}}
test('authenticated administrator reads work, require CSRF, and logout invalidates the session',async()=>{const {cookie,user}=await login('admin@example.test');assert.equal(user.role,'super_admin');for(const route of ['/api/admin/appointments','/api/admin/doctors','/api/admin/staff','/api/admin/audit-events'])assert.equal((await request(route,'GET',null,cookie)).status,200,route);assert.equal((await request('/api/admin/staff','POST',{},cookie)).status,403);assert.equal((await request('/api/logout','POST',{},cookie,user.csrfToken)).status,204);assert.equal((await request('/api/me','GET',null,cookie)).status,401)});
test('viewer cannot mutate patients or doctors or read staff/audit information',async()=>{const {cookie,user}=await login('viewer@example.test');for(const route of ['/api/admin/staff','/api/admin/audit-events'])assert.equal((await request(route,'GET',null,cookie)).status,403);for(const [route,method] of [['/api/admin/doctors','POST'],['/api/admin/appointments/00000000-0000-4000-8000-000000000011/archive','PATCH'],['/api/appointments/00000000-0000-4000-8000-000000000011','PATCH']])assert.equal((await request(route,method,{},cookie,user.csrfToken)).status,403)});
test('physician connection failures produce safe errors and the server remains alive',async()=>{const {cookie,user}=await login('admin@example.test');for(const route of ['/api/admin/doctors','/api/admin/doctors/00000000-0000-4000-8000-000000000011']){const response=await request(route,route.endsWith('doctors')?'POST':'PATCH',{},cookie,user.csrfToken);assert.equal(response.status,500);const body=await response.json();assert.ok(body.reference);assert.doesNotMatch(JSON.stringify(body),/Sensitive connection/)}assert.equal((await request('/health')).status,200)});
test('booking validates consent, accepts a pending request and prevents duplicate slots',async()=>{const doctors=await(await request('/api/doctors')).json();const doctor=doctors[0];const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts().filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));const date=`${parts.year}-${parts.month}-${parts.day}`;const payload={doctorId:doctor.id,date,time:'09:00',fullName:'Fixture Patient',phone:'09171234567',service:'other',smsConsent:false};assert.equal((await request('/api/appointments','POST',payload)).status,400);payload.smsConsent=true;const response=await request('/api/appointments','POST',payload);assert.equal(response.status,201);const result=await response.json();assert.equal(result.status,'pending');assert.match(result.reference,/^BH-/);assert.doesNotMatch(result.message,/SMS reminder is scheduled/);assert.equal((await request('/api/appointments','POST',payload)).status,400);const slots=await(await request(`/api/doctors/${doctor.id}/slots?date=${date}`)).json();assert.equal(slots.slots.find(s=>s.time==='09:00').available,false)});
